# This is a basic workflow to help you get started with Actions

name: CI (self-hosted)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2

    - name: Docker pull
      run: docker pull evandroamparo/delphi2007-build

    - name: Build
      run: docker run -v ${pwd}:C:\app --rm evandroamparo/delphi2007-build cmd /c "cd C:\app & build.cmd" 

    - name: Test
      run: test.cmd

    - name: Compile installer
      run: docker run -v ${pwd}:C:\app --rm evandroamparo/delphi2007-build cmd /c "cd C:\app & setup.cmd" 
